### ISSUE TITLE
Lab Report 2 Feedback

### ISSUE THREAD

**Issue by joy002** [eunkjm/cse15l-lab-reports#2]
**Bug/Input 1**
- [x] Commit screenshot for bug/input 1
- [x] Link to test file for bug/input 1
- [x] Symptom shown as command + output for bug/input 1
- [x] Description of relationship between bug, symptom, and input for bug/input 1

**Bug/Input 2**
- [x] Commit screenshot for bug/input 2
- [x] Link to test file for bug/input 2
- [x] Symptom shown as command + output for bug/input 2
- [x] Description of relationship between bug, symptom, and input for bug/input 2

**Bug/Input 3**
- [x] Commit screenshot for bug/input 3
- [x] Link to test file for bug/input 3
- [x] Symptom shown as command + output for bug/input 3
- [x] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:
Please finish the lab report. Come to office hour if you need any assistance.

Feel free to comment below if you have any questions about the rubric/feedback.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by eunkjm** [comment]
Hello,
I am so sorry for doing this, but I forgot I was supposed to submit the regrade request through the gradescope.
Earlier, I contacted the Professor for extension of deadline to resubmit the lab report 2. He thankfully granted it, but I wasn't notified what the new deadline was. I guess I missed the window because I don't see the regrade request option available.
Could you please look at this link for lab report 2? https://github.com/eunkjm/cse15l-lab-reports/blob/main/lab-report-2-week-4.md
I will contact the professor again, ask if he could open up the regrade request on gradescope again and get back to you if I hear back from him.

**Comment by joy002** [comment]
Please paste the link to the website next time. I have read your website and yes please get back to me if the professor agree with late regrade request.

**Comment by eunkjm** [comment]
Hello, Professor has opened up the regrade request on the gradescope, so I submitted one with the link to this issue and link to the lab report page. If you could take a look at it, I would greatly appreciate it. Thank you!

**Comment by joy002** [comment]
Yes, thank you for letting me know, I have updated your grade. Feel free to comment if there is any other questions, otherwise, please close the issue. Thank you :)
